### PR TITLE
Fix layout

### PR DESCRIPTION
**Pull request by dvwright**
Hi @ovvn In the new version, the layout is 'off' for me. The produced PDF overflows and does not all fit within the margins like it used to in the previous version. These changes produce the results I am expecting, like in the old version.

### CODE REVIEW

**Comment by ovvn** [comment]
Hi @dvwright 
I don't see what would cause the issues in the latest version as opposed to previous since we only added the `compression` parameter. Could you provide the produced PDF generated in version 0.2.0 vs in 0.2.1?

**Comment by dvwright** [comment]
I was actually using 0.1.2 and just upgraded to 0.2.1. The layout has definitely changed for me. I'm creating multipage PDF's based on an html table layout, maybe it's specific to my use case. Unfortunately I can't share the PDF's as they are internal reports. Essentially it's like this

Version 0.1.2: 
Screen Shot 2021-04-13 at 11 19 42 PM

Version 0.2.1
Screen Shot 2021-04-13 at 11 19 55 PM

**Comment by ovvn** [comment]
Interesting, the `compress` parameter shouldn't affect margins, need to investigate.

**Comment by gaetandezeiraud** [comment]
Hi, thanks for your work! Same problem here. The right part is cut off.
image
But render correctly in plain html. Working as expected with version 0.1.2.

**Comment by ovvn** [comment]
Hi @Brouilles, try passing `overrideWidth`, e.g. `{ overrideWidth: 900 }`

**Comment by gaetandezeiraud** [comment]
Hi @ovvn and thanks for your awnser.
Same problem. 

image

**Comment by gaetandezeiraud** [comment]
No news?

**Comment by ovvn** [comment]
It turns out that after upgrade from 0.1.2 to 0.2.1 the `a4Width` and `a4Height` constants were swapped incorrectly! Fixed in 09e76c3f97a9359a7da5b77d24cfe8f619bed8af
@Brouilles please update to 0.2.3 and check if the issue's still there.

**Pull request closed without merging**
